<a href="https://colab.research.google.com/github/Lalasa-web/Gen-AI-with-prompt-engineering-/blob/main/Neural_networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
!pip install tensorflow

In [38]:
#NEURAL NETWORKS - RNN
import numpy as np

# Imports Sequential model used to build neural networks layer by layer
from tensorflow.keras.models import Sequential

# Embedding  -> Converts words/numbers into dense vector representations
# SimpleRNN -> Processes sequential data and remembers previous information
# Dense      -> Fully connected layer used for prediction/output
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

# Tokenizer converts text words into numerical tokens (integers)
from tensorflow.keras.preprocessing.text import Tokenizer

# Converts class labels into one-hot encoded format
from tensorflow.keras.utils import to_categorical

# Makes all sequences equal length by adding padding values
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [39]:
sentence = "I love deep learning"

In [40]:
tokenizer = Tokenizer()

In [41]:
tokenizer.fit_on_texts([sentence])

In [42]:
sequence = tokenizer.texts_to_sequences([sentence])[0]

In [43]:
sequence

[1, 2, 3, 4]

In [45]:
x = [] #stores input sequences
y = [] #stores expected outputs
for i in range(1, len(sequence)):
  x.append(sequence[:i])
  y.append(sequence[i])

print("x : ", x)
print()
print("y : ", y)

x :  [[1], [1, 2], [1, 2, 3]]

y :  [2, 3, 4]


In [46]:
x = pad_sequences(x)
print(x)

[[0 0 1]
 [0 1 2]
 [1 2 3]]


In [47]:
x = np.array(x)
y = np.array(y)
print(x)
print("\n", y)

[[0 0 1]
 [0 1 2]
 [1 2 3]]

 [2 3 4]


In [48]:
y = to_categorical(y)
y

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
# Calculates total vocabulary size by counting all unique words
# +1 is added because index 0 is reserved for padding
vocab_size = len(tokenizer.word_index) + 1

In [53]:
# Model creation
model = Sequential()
# Creates an empty neural network model where layers are added one after another

# Embedding layer
model.add(Embedding(input_dim=vocab_size, output_dim=10, input_length=x.shape[1]))
# Converts input word indices into dense vectors
# input_dim = total vocabulary size
# output_dim = each word is represented using a vector of size 10
# input_length = length of each input sequence

# RNN layer
model.add(SimpleRNN(20))
# Adds a Simple Recurrent Neural Network layer with 20 neurons
# This layer processes sequential data and remembers previous information

# Dense layer
model.add(Dense(vocab_size, activation='softmax'))
# Output layer with number of neurons equal to vocabulary size
# softmax activation gives probability for predicting the next word

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [59]:
#compile
#Optimizer → learns by updating weights
#Loss Function → measures mistakes
#Accuracy → measures performance
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Trains the neural network using input data (x) and output data (y)
# epochs=500 -> the model learns from the entire dataset 500 times
# verbose=0 -> hides training progress/output during training
model.fit(x, y, epochs = 500, verbose = 0)

test_text = "I love deep"
test_seq = tokenizer.texts_to_sequences([test_text])
test_seq


[[1, 2, 3]]

In [61]:
test_seq = pad_sequences(test_seq, maxlen=x.shape[1])
test_seq

array([[1, 2, 3]], dtype=int32)

In [62]:
prediction = model.predict(test_seq)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step


In [63]:
prediction

array([[1.1312910e-08, 1.9779556e-08, 1.6366144e-08, 1.5738199e-09,
        1.0000000e+00]], dtype=float32)

In [65]:
predicted_index = np.argmax(prediction)
# Finds the index of the highest value in the prediction array
# The index represents the predicted word/class

predicted_index
# Displays the predicted index value

np.int64(4)

In [101]:
#LSTM - Long Shot-term Memory : used to store information for long period of time
#since rnn forgets previous information and causes vanishing gradient problem , lstm is used which is an advanced rnn
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.sequence import pad_sequences

sentence = "I love pizza"

tokenizer = Tokenizer()

tokenizer.fit_on_texts([sentence])

sequence = tokenizer.texts_to_sequences([sentence])[0]
print("sequence : ")
print(sequence)
print()

x = []
y = []
for i in range(1, len(sequence)):
    x.append(sequence[:i])
    y.append(sequence[i])

print("x : ", x)
print("y : ", y)
print()

print("x after padding : ")
x = pad_sequences(x)
print(x)
print()

x = np.array(x)
y = np.array(y)

print("After performing to_categorical on output sequence y  : ")
y = to_categorical(y)
print(y)
print()

vocab_size = len(tokenizer.word_index) + 1
print("vocab size : ", vocab_size)

model = Sequential()
#Embedding layer
model.add(Embedding(input_dim=vocab_size, output_dim=10, input_length=x.shape[1]))
#LSTM layer
model.add(LSTM(20))
#Dense layer
model.add(Dense(vocab_size, activation='softmax'))

#compile
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(x, y, epochs=500, verbose=0)

test_text = "I love"
test_seq = tokenizer.texts_to_sequences([test_text])
test_seq = pad_sequences(test_seq, maxlen=x.shape[1])
print("Test sequence : ", test_seq)
print()

prediction = model.predict(test_seq)
print("prediction : ", prediction)
print()
predicted_index = np.argmax(prediction)
print("Predicted Index : ", predicted_index)

for word, index in tokenizer.word_index.items():
    if index == predicted_index:
        print("Predicted Word : ", word)
        break



sequence : 
[1, 2, 3]

x :  [[1], [1, 2]]
y :  [2, 3]

x after padding : 
[[0 1]
 [1 2]]

After performing to_categorical on output sequence y  : 
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]]

vocab size :  4
Test sequence :  [[1 2]]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step
prediction :  [[6.4930813e-05 8.1984414e-05 1.8883020e-03 9.9796486e-01]]

Predicted Index :  3
Predicted Word :  pizza
