<a href="https://colab.research.google.com/github/Lalasa-web/Gen-AI-with-prompt-engineering-/blob/main/Encoder_and_Decoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
#Encoder and decoder

#ENCODER

# Imports TensorFlow library
# Used for tensors, neural networks, and deep learning operations
import tensorflow as tf

# Example sentence : "I eat apples"

# Each vector represents one word in the sentence
# I      -> [1.0, 0.0]
# eat    -> [0.0, 1.0]
# apples -> [1.0, 1.0]

# Creates a TensorFlow tensor for encoder input
# Shape = (1,3,2)
# 1 -> batch size
# 3 -> number of words in sentence
# 2 -> features/embedding size for each word
encoder_input = tf.constant([[[1.0, 0.0],
                             [0.0, 1.0],
                             [1.0, 1.0]]], dtype = tf.float32)

# Stores dimensions of the encoder input
# batch_size = number of sentences
# sequence_length = number of words
# features = embedding size of each word
(batch_size, sequence_length, features) = 1, 3, 2

# Prints the encoder input tensor
print("encoder input : " , encoder_input)
print()

#Encoder self-attention

# Creates a Multi-Head Attention layer
# num_heads=2 -> uses 2 attention heads
# key_dim=2 -> each Query and Key vector has dimension 2

# Head1 -> may learn grammar relationships
# Head2 -> may learn semantic meaning/context
encoder_attention = tf.keras.layers.MultiHeadAttention(
    num_heads = 2,
    key_dim = 2
)

# attention(query, value)
# Here:
# Query = encoder_input
# Key   = encoder_input (automatically same as value if not given)
# Value = encoder_input

# Applies self-attention on encoder input
# Each word attends to all other words in the sentence
# Produces context-aware word representations
encoder_output = encoder_attention(encoder_input, encoder_input)

# Prints the shape of encoder output tensor
print("encoder output : " , encoder_output.shape)
print()
print("encoder output: ", encoder_output)

encoder input :  tf.Tensor(
[[[1. 0.]
  [0. 1.]
  [1. 1.]]], shape=(1, 3, 2), dtype=float32)

encoder output :  (1, 3, 2)

encoder output:  tf.Tensor(
[[[0.68136775 1.1343877 ]
  [0.71231866 1.1312909 ]
  [0.67885095 1.1457486 ]]], shape=(1, 3, 2), dtype=float32)


In [39]:
#DECODER

# Creates decoder input tensor
# Shape = (1,3,2)
# 1 -> batch size
# 3 -> number of words/tokens
# 2 -> embedding/features size
decoder_input = tf.constant([[[0.68136775, 1.1343877 ],
                              [0.71231866, 1.1312909 ],
                              [0.67885095, 1.1457486 ]]], dtype = tf.float32)

# Prints decoder input tensor
print("decoder input: ", decoder_input)
print()

# Creates Multi-Head Attention layer for decoder self-attention
# num_heads=2 -> uses 2 attention heads
# key_dim=2 -> Query and Key vector size is 2
decoder_attention = tf.keras.layers.MultiHeadAttention(
    num_heads = 2,
    key_dim = 2
)

# Applies masked self-attention on decoder input
# Query = decoder_input
# Key = decoder_input
# Value = decoder_input
# use_causal_mask=True prevents decoder from seeing future words
decoder_output = decoder_attention(decoder_input, decoder_input, use_causal_mask = True)

# Prints decoder self-attention output
print("decoder output: ", decoder_output)
print()

# Prints shape of decoder output tensor
print("decoder output shape: ", decoder_output.shape)
print()

# Creates another Multi-Head Attention layer
# Used for encoder-decoder attention (cross-attention)
cross_attention = tf.keras.layers.MultiHeadAttention(
    num_heads = 2,
    key_dim = 2
)

# Applies encoder-decoder attention
# Query comes from decoder output
# Key and Value come from encoder output
# Decoder focuses on important encoder information
final_decoder = cross_attention(
    query = decoder_output,
    value = encoder_output,
    key = encoder_output
)

# Prints final decoder output after cross-attention
print("final decoder: ", final_decoder)



decoder input:  tf.Tensor(
[[[0.68136775 1.1343877 ]
  [0.71231866 1.1312909 ]
  [0.67885095 1.1457486 ]]], shape=(1, 3, 2), dtype=float32)

decoder output:  tf.Tensor(
[[[-0.6328943   0.20869508]
  [-0.64180136  0.2112655 ]
  [-0.63907486  0.21055773]]], shape=(1, 3, 2), dtype=float32)

decoder output shape:  (1, 3, 2)

final decoder:  tf.Tensor(
[[[-0.8988033  1.0162572]
  [-0.8988031  1.0162573]
  [-0.8988033  1.0162573]]], shape=(1, 3, 2), dtype=float32)
